export type EntryStatus = 'captured' | 'processing' | 'extracted';

export type IntakeKey = 'make' | 'forWho' | 'rules';

export type Entry = {
  id: string;
  title: string;
  createdAt: number;
  kind: 'voice' | 'text' | 'import' | 'upload' | 'video';
  status: EntryStatus;
  intent?: string;
  targetFormat?: Draft['format'];
  durationSec?: number;
  audioUri?: string;
  audioMimeType?: string;
  mediaBucket?: string;
  mediaPath?: string;
  mediaFilename?: string;
  mediaSizeBytes?: number;
  mediaSha256?: string;
  mediaMimeType?: string;
  transcript?: string;
  intakeKey?: IntakeKey;
  highlights?: string[];
  themes?: string[];
  ideas?: { title: string; detail?: string }[];
  projectId?: string;
};

export type ProjectType = 'standard' | 'book';

export type CanonCard = {
  id: string;
  kind: 'character' | 'world' | 'theme' | 'claim' | 'timeline';
  title: string;
  detail: string;
  updatedAt: number;
};

export type NarrativeStage =
  | 'premise'
  | 'introduction'
  | 'early-conflict'
  | 'discovery'
  | 'first-success'
  | 'escalation'
  | 'pressure'
  | 'setback'
  | 'reinvention'
  | 'return'
  | 'confrontation'
  | 'climax'
  | 'resolution';

export type OutlineItem = {
  id: string;
  title: string;
  note?: string;
  stage?: NarrativeStage;
  autoGenerated?: boolean;
};

export type BookAssets = {
  brief: {
    premise: string;
    audience: string;
    tone: string;
    constraints: string;
  };
  outline: OutlineItem[];
  canon: CanonCard[];
};

export type Project = {
  id: string;
  name: string;
  type: ProjectType;
  createdAt: number;
  pinned: boolean;
  entryIds: string[];
  draftIds: string[];
  book?: BookAssets;
};

export type DraftTone = 'neutral' | 'reflective' | 'funny' | 'serious';
export type DraftDistance = 'close' | 'expand' | 'invent';

export type Draft = {
  id: string;
  projectId?: string;
  entryIds: string[];
  targetOutlineItemId?: string;
  title: string;
  createdAt: number;
  format: 'essay' | 'commentary' | 'podcast-outline' | 'script' | 'thread' | 'book-chapter';
  tone: DraftTone;
  distance: DraftDistance;
  content: string;
  version: number;
};

export type StudioMode = 'interview' | 'outline' | 'draft';

export type AppSettings = {
  apiBaseUrlOverride?: string;
  ashtonModeEnabled: boolean;
  ashtonVoiceNotes: string;
};

export type AuthState = {
  status: 'unknown' | 'signedOut' | 'signedIn';
  userId?: string;
  email?: string;
};

export type UserProfile = {
  id: string;
  email?: string;
  displayName: string;
  handle?: string;
  testingLabel?: string;
  outputVisibility?: 'private' | 'public';
  workflowFocus?: 'studio' | 'vault' | 'projects' | 'mixed';
  createdAt?: number;
  updatedAt?: number;
  lastSeenAt?: number;
};

export type ProfileState = {
  status: 'idle' | 'loading' | 'ready' | 'error';
  record?: UserProfile;
  lastError?: string;
};

export type SyncState = {
  status: 'idle' | 'syncing' | 'error';
  lastSyncAt?: number;
  lastError?: string;
};

export type AppState = {
  entries: Record<string, Entry>;
  projects: Record<string, Project>;
  drafts: Record<string, Draft>;
  settings: AppSettings;
  auth: AuthState;
  profile: ProfileState;
  sync: SyncState;
  studio: {
    activeProjectId?: string;
    modeByProjectId: Record<string, StudioMode>;
    draftSelectionByProjectId: Record<string, { entryIds: string[]; factIds: string[] }>;
    draftStyleByProjectId: Record<string, { tone: DraftTone; distance: DraftDistance; targetOutlineItemId?: string }>;
  };
};

export type AppAction =
  | { type: 'app.hydrate'; payload: { state: AppState } }
  | {
      type: 'app.replaceRemoteData';
      payload: {
        entries: Record<string, Entry>;
        projects: Record<string, Project>;
        drafts: Record<string, Draft>;
      };
    }
  | { type: 'auth.set'; payload: { userId: string; email?: string } }
  | { type: 'auth.clear' }
  | { type: 'profile.set'; payload: { record: UserProfile } }
  | { type: 'profile.clear' }
  | { type: 'profile.setStatus'; payload: { status: ProfileState['status']; lastError?: string } }
  | { type: 'sync.set'; payload: { status: SyncState['status']; lastSyncAt?: number; lastError?: string } }
  | { type: 'settings.setApiBaseUrlOverride'; payload: { value?: string } }
  | { type: 'settings.resetApiBaseUrlOverride' }
  | { type: 'settings.setAshtonModeEnabled'; payload: { value: boolean } }
  | { type: 'settings.setAshtonVoiceNotes'; payload: { value: string } }
  | {
      type: 'entry.createText';
      payload: {
        entryId?: string;
        title?: string;
        text: string;
        intent?: string;
        targetFormat?: Draft['format'];
        intakeKey?: IntakeKey;
        kind?: 'text' | 'voice';
        durationSec?: number;
      };
    }
  | { type: 'entry.createImportTranscript'; payload: { entryId?: string; title?: string; transcript: string; intent?: string; targetFormat?: Draft['format']; intakeKey?: IntakeKey } }
  | {
      type: 'entry.createRecording';
      payload: { entryId?: string; title?: string; intent?: string; targetFormat?: Draft['format']; intakeKey?: IntakeKey; durationSec?: number; audioUri: string; audioMimeType?: string };
    }
  | {
      type: 'entry.createUpload';
      payload: {
        entryId?: string;
        title?: string;
        kind: 'upload' | 'video';
        localUri: string;
        filename?: string;
        sizeBytes?: number;
        mimeType?: string;
        mediaBucket?: string;
        mediaPath?: string;
        mediaSha256?: string;
      };
    }
  | { type: 'entry.setStatus'; payload: { entryId: string; status: EntryStatus } }
  | {
      type: 'entry.setExtraction';
      payload: {
        entryId: string;
        title?: string;
        transcript: string;
        highlights: string[];
        themes: string[];
        ideas: { title: string; detail?: string }[];
      };
    }
  | { type: 'project.create'; payload: { projectId?: string; name: string; projectType: ProjectType; targetChapterCount?: number } }
  | { type: 'project.togglePinned'; payload: { projectId: string } }
  | { type: 'project.addEntry'; payload: { projectId: string; entryId: string } }
  | { type: 'project.setEntries'; payload: { projectId: string; entryIds: string[] } }
  | {
      type: 'draft.create';
      payload: { draftId?: string; projectId?: string; entryIds: string[]; format: Draft['format']; title?: string; content?: string; tone?: DraftTone; distance?: DraftDistance; targetOutlineItemId?: string };
    }
  | {
      type: 'draft.update';
      payload: { draftId: string; content: string; title?: string };
    }
  | {
      type: 'draft.commitSnapshot';
      payload: { sourceDraftId: string; draftId?: string; title?: string; content?: string };
    }
  | { type: 'studio.setMode'; payload: { projectId: string; mode: StudioMode } }
  | { type: 'studio.setDraftSelection'; payload: { projectId: string; entryIds: string[]; factIds: string[] } }
  | { type: 'book.setBrief'; payload: { projectId: string; brief: BookAssets['brief'] } }
  | { type: 'book.addCanonCard'; payload: { projectId: string; kind: CanonCard['kind']; title: string; detail: string } }
  | { type: 'book.updateCanonCard'; payload: { projectId: string; canonCardId: string; kind?: CanonCard['kind']; title?: string; detail?: string } }
  | { type: 'book.removeCanonCard'; payload: { projectId: string; canonCardId: string } }
  | { type: 'book.materializeNarrativeOutline'; payload: { projectId: string } }
  | { type: 'book.addOutlineItem'; payload: { projectId: string; title: string; note?: string } }
  | { type: 'studio.setDraftStyle'; payload: { projectId: string; tone?: DraftTone; distance?: DraftDistance; targetOutlineItemId?: string } }
  | { type: 'book.updateOutlineItem'; payload: { projectId: string; outlineItemId: string; title?: string; note?: string } };
